import { Sparkles } from 'lucide-react';

export default function AISummary({ summary, keyPoints }) {
  if (!summary) return null;

  return (
    <div className="bg-gradient-to-br from-purple-50 to-blue-50 border border-purple-100 rounded-2xl p-6 mb-8 shadow-sm">
      <div className="flex items-center gap-2 text-purple-800 font-bold mb-3 uppercase tracking-wider text-xs">
        <Sparkles size={16} className="text-purple-600 animate-pulse" />
        AI Key Insights
      </div>
      
      <p className="text-slate-700 leading-relaxed mb-4 text-lg italic">
        "{summary}"
      </p>

      {keyPoints?.length > 0 && (
        <div className="space-y-3 pt-4 border-t border-purple-100/50">
          {keyPoints.map((point, i) => (
            <div key={i} className="flex items-start gap-3">
              <div className="mt-1.5 w-1.5 h-1.5 rounded-full bg-blue-400 flex-shrink-0" />
              <p className="text-sm text-slate-600 leading-relaxed">{point}</p>
            </div>
          ))}
        </div>
      )}
      
      <div className="mt-6 flex items-center justify-between">
        <p className="text-[10px] text-purple-400 font-medium tracking-tight">
          Powered by OpenRouter AI • Generated by BlogNivo Engine
        </p>
      </div>
    </div>
  );
}